version: '3'

services:
  web:
    build: .
    restart: on-failure
    container_name: my-django-app

    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

    command: sh migrate_and_run.sh

    environment:
      - DEBUG=True  
      - HOST=db
      - PORT=5432
      - NAME=mydatabase
      - USER=myuser
      - PASSWORD=mypassword

      - REDIS_HOST=redis
      - REDIS_PORT=6379

    volumes:
      - ./mysite:/app/mysite 

  celery:
    build: .

    container_name: celery

    command: sh start_worker.sh

    environment:
      - DEBUG=True  
      - HOST=db
      - PORT=5432
      - NAME=mydatabase
      - USER=myuser
      - PASSWORD=mypassword

      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
    depends_on:
      - db
      - redis
      - web
 
  redis:
    image: redis:latest
    container_name: redis-server

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

    ports:
      - "5432:5432"



  
