# Generated by Django 4.2.5 on 2023-09-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%d_%m_%Y')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
